name: BrightSec Full Scan

on:
  push:
    branches:
      - main

jobs:
  brightsec-full-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run a Bright Discovery
        id: run_discovery
        uses: NeuraLegion/run-discovery@v1.1
        with:
          api_token: ${{ secrets.BRIGHTSEC_TOKEN }} 
          project_id: ${{ vars.PROJECT_ID }} 
          #hostname: ${{ vars.HOSTNAME }} 
          auth_object_id: ${{ vars.AUTH_ID }} 
          discovery_types: '[ "crawler"]' 
          crawler_urls: '[ "https://crapi-pure-duck-8.k3s.brokencrystals.nexploit.app/login"]' 
          name: GitHub discovery ${{ github.sha }}
          concurrency: 5 
          interactions_depth: 3 
          smart: true 
         # restart_discovery_id: # optional
          # file_id: # optional
          # repeaters: # optional
          # smart: # optional
          # hosts_filter: # optional
          # crawl_parent_subdomains: # optional
          
          
      - name: Get the output discovery url
        id: extract_id
        run: |
            url="${{ steps.run_discovery.outputs.url }}"
            id="${url##*/}"
            echo "Discovery ID is: $id"
            echo "discovery_id=$id" >> $GITHUB_OUTPUT
  
      - name: List Project Entrypoints
        id: entrypoints
        uses: NeuraLegion/list-entrypoints@v1
        with:
          api_token: ${{ secrets.BRIGHTSEC_TOKEN  }}
          project_id: ${{ vars.PROJECT_ID }}
          hostname: https://app.brightsec.com/ 
          limit: 10
          connectivity: ok,unreachable
          status: new,vulnerable
         
      - name: Run a Bright Security Scan
        id: run_scan
        uses: NeuraLegion/run-scan@v1.3
        with:
          api_token: ${{ secrets.BRIGHTSEC_TOKEN }}
          project_id: ${{ vars.PROJECT_ID }}
          hostname: ${{ vars.HOSTNAME }}
          name: Scan ${{ github.sha }}
          entrypoints: ${{ steps.entrypoints.outputs.entrypoints }}
          module: "dast"
          tests: '["cookie_security"]'
          # restart_scan: # optional
          # file_id: # optional
          # repeaters: # optional (if used needs to be added in AO flow as well as Disocvery)
          # exclude_entry_points: # optional
          # module: # optional (dast, fuzzer)
          # hosts_filter: # optional
          
      # - name: Stop Bright Security Scan
      #   uses: NeuraLegion/stop-scan@v1 
