name: BrightSec Full Scan

on:
  push:
    branches:
      - main

jobs:
  brightsec-full-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run a Bright Discovery
        id: run_discovery
        uses: NeuraLegion/run-discovery@v1.1
        with:
          api_token: ${{ secrets.BRIGHTSEC_TOKEN }} 
          project_id: ${{ vars.PROJECT_ID }} 
          hostname: ${{ vars.HOSTNAME }} 
          auth_object_id: ${{ vars.AUTH_ID }} 
          discovery_types: '[ "crawler" ]' 
          crawler_urls: '[ "https://brokencrystals.com" ]' 
          name: GitHub discovery ${{ github.sha }}
          concurrency: 10 
          interactions_depth: 3 
          smart: true 
         # restart_discovery_id: # optional
          # file_id: # optional
          # repeaters: # optional
          # smart: # optional
          # hosts_filter: # optional
          # crawl_parent_subdomains: # optional
          
          
      - name: Get the output discovery url
        id: extract_id
        run: |
            url="${{ steps.run_discovery.outputs.url }}"
            id="${url##*/}"
            echo "Discovery ID is: $id"
            echo "discovery_id=$id" >> $GITHUB_OUTPUT

      - name: Wait for Bright discovery
        id: wait_discovery
        uses: NeuraLegion/wait-for-discovery@v1
        with:
          api_token: ${{ secrets.BRIGHTSEC_TOKEN }}
          discovery_id: ${{ steps.extract_id.outputs.discovery_id }}
          project_id: ${{ vars.PROJECT_ID }}
          timeout: 900
          hostname: ${{ vars.HOSTNAME }}
  
      - name: List Project Entrypoints
        id: entrypoints
        uses: NeuraLegion/list-entrypoints@v1
        with:
          api_token: ${{ secrets.BRIGHTSEC_TOKEN  }}
          project_id: ${{ vars.PROJECT_ID }}
          hostname: https://eu.brightsec.com/ 
          limit: 50
          connectivity: ok,unreachable
          status: new,vulnerable

      - name: Save Entrypoints
        id: parse_entrypoints
        run: |
          echo "entrypoints=${{ steps.entrypoints.outputs.entrypoints }}" >> $GITHUB_OUTPUT
         
      - name: Run a Bright Security Scan
        id: run_scan
        uses: NeuraLegion/run-scan@v1.3
        with:
          api_token: ${{ secrets.BRIGHTSEC_TOKEN }}
          project_id: ${{ vars.PROJECT_ID }}
          hostname: ${{ vars.HOSTNAME }}
          name: Scan ${{ github.sha }}
          entrypoints: ${{ steps.parse_entrypoints.outputs.entrypoints }}
          module: "dast"
          tests: '["amazon_s3_takeover","jwt","broken_saml_auth","brute_force_login","common_files","cookie_security","csrf","xss","css_injection","default_login_location","directory_listing","email_injection","file_upload","full_path_disclosure","graphql_introspection","header_security","html_injection","http_method_fuzzing","iframe_injection","improper_asset_management","insecure_tls_configuration","ldapi","lfi","nosql","open_cloud_storage","open_database","osi","proto_pollution","rfi","secret_tokens","ssti","server_side_js_injection","ssrf","sqli","stored_xss","unvalidated_redirect","version_control_systems","wordpress","xxe","xpathi","bopla","business_constraint_bypass","date_manipulation","excessive_data_exposure","id_enumeration","cve_test","retire_js"]'
          # restart_scan: # optional
          # file_id: # optional
          # repeaters: # optional (if used needs to be added in AO flow as well as Disocvery)
          # exclude_entry_points: # optional
          # module: # optional (dast, fuzzer)
          # hosts_filter: # optional
          
      # - name: Stop Bright Security Scan
      #   uses: NeuraLegion/stop-scan@v1 
