name: BrightSec Full Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger from UI

jobs:
  brightsec-full-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Bright Security Scan
        uses: NeuraLegion/run-scan@v1.3
        with:
          api_token: ${{ secrets.BRIGHTSEC_TOKEN }}
          project_id: ${{ vars.PROJECT_ID }}

          # Name of the scan
          name: Scan ${{ github.sha }}

          # Let scan handle discovery automatically
          discovery_types: '[ "crawler" ]'
          crawler_urls: '[ "https://dvwa-lit-duck-8.k3s.brokencrystals.nexploit.app/" ]'

          # Optional: include auth if your app needs login
          # auth_object_id: ${{ vars.AUTH_ID }}

          # Scan type
          module: "dast"

          # Start small (expand later if needed)
          tests: '["cookie_security"]'
